import time
from selenium.webdriver.common.by import By
from core.environment.host import get_host_for_selenium_testing
from core.selenium.common import initialize_driver


class TesttagSizeTitle():

  def setup_method(self, method):
    self.driver = initialize_driver()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_testauthor(self):
    self.driver.get(get_host_for_selenium_testing())
    self.driver.maximize_window()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(3) .align-middle:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(4)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)
    
    self.driver.find_element(By.CSS_SELECTOR, "#tag > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#size > option:nth-child(7)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#title > option:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apply-filters").click()
    time.sleep(1)