"""empty message

Revision ID: 00445c819530
Revises: dd9fc44b4c95
Create Date: 2024-11-09 13:26:54.678556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00445c819530'
down_revision = 'dd9fc44b4c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index('_follower_followed_uc')

    op.drop_table('follow')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('_follower_followed_uc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('_follower_followed_uc', ['follower_id', 'followed_id'], unique=True)

    op.create_table('follow',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('follower_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('followed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('followed_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='follow_ibfk_1'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='follow_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.create_index('_follower_followed_uc', ['follower_id', 'followed_id'], unique=True)

    # ### end Alembic commands ###
