"""empty message

Revision ID: 5f21dffa2228
Revises: b2d011fde821
Create Date: 2024-11-13 13:27:08.312297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f21dffa2228'
down_revision = 'b2d011fde821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notepad')
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index('_follower_followed_uc')
        batch_op.drop_column('followed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False))
        batch_op.create_index('_follower_followed_uc', ['follower_id', 'followed_id'], unique=True)

    op.create_table('notepad',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notepad_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
