"""empty message

Revision ID: 962c0b92f4ba
Revises: 2bc9e80f25d9
Create Date: 2024-12-11 13:35:24.036548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '962c0b92f4ba'
down_revision = '2bc9e80f25d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('usability', sa.Integer(), nullable=False),
    sa.Column('total_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index('_follower_followed_uc')
        batch_op.drop_column('followed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False))
        batch_op.create_index('_follower_followed_uc', ['follower_id', 'followed_id'], unique=True)

    op.drop_table('ratings')
    # ### end Alembic commands ###
