"""create_social_model

Revision ID: c21fad30c262
Revises: 
Create Date: 2024-11-09 12:52:17.540085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21fad30c262'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.Column('comment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('follower', sa.Integer(), nullable=False),
    sa.Column('followed', sa.Integer(), nullable=False),
    sa.Column('data_set', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_set'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['followed'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social')
    # ### end Alembic commands ###
