name: Codacy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
        env:
          CHROMEWEBDRIVER: /usr/local/bin

      - name: Run Selenium Tests
        id: selenium-tests
        run: |
          pytest --tb=short tests/selenium/ --junitxml=selenium-results.xml || echo "Selenium Tests failed"
        continue-on-error: true

      - name: Run Unit Tests
        id: unit-tests
        run: |
          pytest --tb=short tests/unit/ --junitxml=unit-results.xml || echo "Unit Tests failed"
        continue-on-error: true

      - name: Create Issue for Failed Selenium Tests
        if: steps.selenium-tests.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'ErrorCodacy-PruebasSelenium',
              body: 'Las pruebas de Selenium fallaron. Por favor, revisar los logs para más detalles.'
            });

      - name: Create Issue for Failed Unit Tests
        if: steps.unit-tests.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'ErrorCodacy-PruebasUnitarias',
              body: 'Las pruebas unitarias fallaron. Por favor, revisar los logs para más detalles.'
            });

      - name: Upload coverage to Codacy
        run: |
          pip install codacy-coverage
          coverage run -m pytest app/modules/
          coverage xml
          python-codacy-coverage -r coverage.xml
        env:
          FLASK_ENV: testing
          MARIADB_HOSTNAME: 127.0.0.1
          MARIADB_PORT: 3306
          MARIADB_TEST_DATABASE: uvlhubdb_test
          MARIADB_USER: uvlhub_user
          MARIADB_PASSWORD: uvlhub_password
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
