name: Commit Message Format Checker

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit_message
        run: |
          message=$(git log -1 --pretty=%B)
          echo "Commit message: $message"
          echo "::set-output name=message::$message"

      - name: Check commit message
        run: |
          message="${{ steps.commit_message.outputs.message }}"
          pattern="^(feat|fix|style|refactor|test)\([^\)]+\):\s.+\s#\d+$"
          if [[ ! "$message" =~ $pattern ]]; then
            echo "Error: El mensaje del commit no sigue el formato esperado"
            echo "Formato esperado: <tipo>(<WI>): <descripción> #<número issue>"
            echo "Ejemplo válido: feat(Funcionalidad): Nuevos cambios #6 y #8"
            exit 1
          fi