name: Comprobar mensaje del commits

on:
  pull_request:
  push:

jobs:
  comprobar-mensaje-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check commit message
        id: commit_message
        run: |
          message=$(git log --format=%s -n 1)
          echo "Commit message: $message"
          pattern="^(feat|fix|style|refactor|test)\([^\)]+\):\s.+\s?#\d+$"
          if [[ ! "$message" =~ $pattern ]]; then
            echo "Error: El mensaje del commit no sigue el formato esperado"
            echo "Formato esperado: <tipo>(<WI>): <descripción> #<número issue>"
            echo "Ejemplo válido: feat(Funcionalidad): Nuevos cambios #6"
            exit 1
          fi